include "constants/unit_constants.inc"

; two 52-entry unit-type-indexed list-profile tables used by the
; tactical scorer. The tables cover real unit types 0-51 and exclude DUMMY.
; List contents are symbolic; policy/weight meaning remains deliberately neutral.


section "Map AI Tactical Unit-Type List Profiles", romx[$4a43], bank[$0d]

MapAI_TargetPriorityListTable::
MapAI_UnitTypeListProfileTableA:: ; compatibility name
    dw MapAI_UnitTypeListA_None ;  0 UNIT_TYPE_EMPTY
    dw MapAI_UnitTypeListA_None ;  1 UNIT_TYPE_INFANTRY
    dw MapAI_UnitTypeListA_GroundHeavy ;  2 UNIT_TYPE_MISSILE_INFANTRY
    dw MapAI_UnitTypeListA_None ;  3 UNIT_TYPE_MERCENARY_INFANTRY
    dw MapAI_UnitTypeListA_None ;  4 UNIT_TYPE_CONSTRUCTION_TRUCK
    dw MapAI_UnitTypeListA_None ;  5 UNIT_TYPE_SUPPLY_TRUCK
    dw MapAI_UnitTypeListA_None ;  6 UNIT_TYPE_SUPPLY_TRUCK_S
    dw MapAI_UnitTypeListA_None ;  7 UNIT_TYPE_TRANSPORT_TRUCK
    dw MapAI_UnitTypeListA_None ;  8 UNIT_TYPE_TRANSPORT_TRUCK_S
    dw MapAI_UnitTypeListA_None ;  9 UNIT_TYPE_COMBAT_BUGGY
    dw MapAI_UnitTypeListA_None ; 10 UNIT_TYPE_COMBAT_BUGGY_S
    dw MapAI_UnitTypeListA_None ; 11 UNIT_TYPE_COMBAT_VEHICLE
    dw MapAI_UnitTypeListA_None ; 12 UNIT_TYPE_COMBAT_VEHICLE_S
    dw MapAI_UnitTypeListA_None ; 13 UNIT_TYPE_APC
    dw MapAI_UnitTypeListA_None ; 14 UNIT_TYPE_APC_S
    dw MapAI_UnitTypeListA_BroadNonAir ; 15 UNIT_TYPE_ROCKET_LAUNCHER
    dw MapAI_UnitTypeListA_BroadNonAir ; 16 UNIT_TYPE_ROCKET_LAUNCHER_S
    dw MapAI_UnitTypeListA_None ; 17 UNIT_TYPE_ANTI_AIR_TANK
    dw MapAI_UnitTypeListA_None ; 18 UNIT_TYPE_MERCENARY_ANTI_AIR_MISSILES
    dw MapAI_UnitTypeListA_Air ; 19 UNIT_TYPE_ANTI_AIR_MISSILES
    dw MapAI_UnitTypeListA_Air ; 20 UNIT_TYPE_ANTI_AIR_MISSILES_S
    dw MapAI_UnitTypeListA_BroadNonAir ; 21 UNIT_TYPE_ARTILLERY
    dw MapAI_UnitTypeListA_BroadNonAir ; 22 UNIT_TYPE_ARTILLERY_S
    dw MapAI_UnitTypeListA_None ; 23 UNIT_TYPE_IFV
    dw MapAI_UnitTypeListA_GroundHeavy ; 24 UNIT_TYPE_IFV_S
    dw MapAI_UnitTypeListA_None ; 25 UNIT_TYPE_TANK_DESTROYER
    dw MapAI_UnitTypeListA_GroundHeavy ; 26 UNIT_TYPE_TANK_DESTROYER_S
    dw MapAI_UnitTypeListA_None ; 27 UNIT_TYPE_TANK
    dw MapAI_UnitTypeListA_None ; 28 UNIT_TYPE_MERCENARY_TANK
    dw MapAI_UnitTypeListA_None ; 29 UNIT_TYPE_FIGHTER_PLANE_A
    dw MapAI_UnitTypeListA_None ; 30 UNIT_TYPE_FIGHTER_PLANE_B
    dw MapAI_UnitTypeListA_Air ; 31 UNIT_TYPE_FIGHTER_PLANE_S
    dw MapAI_UnitTypeListA_None ; 32 UNIT_TYPE_ATTACK_PLANE_A
    dw MapAI_UnitTypeListA_None ; 33 UNIT_TYPE_ATTACK_PLANE_B
    dw MapAI_UnitTypeListA_None ; 34 UNIT_TYPE_ATTACK_PLANE_S
    dw MapAI_UnitTypeListA_None ; 35 UNIT_TYPE_BOMBER
    dw MapAI_UnitTypeListA_None ; 36 UNIT_TYPE_MERCENARY_BOMBER
    dw MapAI_UnitTypeListA_None ; 37 UNIT_TYPE_TRANSPORT_PLANE
    dw MapAI_UnitTypeListA_None ; 38 UNIT_TYPE_REFUELING_PLANE
    dw MapAI_UnitTypeListA_None ; 39 UNIT_TYPE_BATTLE_HELICOPTER
    dw MapAI_UnitTypeListA_BroadNonAir ; 40 UNIT_TYPE_BATTLE_HELICOPTER_S
    dw MapAI_UnitTypeListA_None ; 41 UNIT_TYPE_ANTI_SUB_HELICOPTER
    dw MapAI_UnitTypeListA_None ; 42 UNIT_TYPE_TRANSPORT_HELICOPTER
    dw MapAI_UnitTypeListA_None ; 43 UNIT_TYPE_TRANSPORT_HELICOPTER_S
    dw MapAI_UnitTypeListA_Naval ; 44 UNIT_TYPE_AEGIS_WARSHIP
    dw MapAI_UnitTypeListA_Air ; 45 UNIT_TYPE_MERCENARY_MISSILE_FRIGATE
    dw MapAI_UnitTypeListA_Air ; 46 UNIT_TYPE_LARGE_CARRIER
    dw MapAI_UnitTypeListA_Air ; 47 UNIT_TYPE_SMALL_CARRIER
    dw MapAI_UnitTypeListA_None ; 48 UNIT_TYPE_TRANSPORT_SHIP
    dw MapAI_UnitTypeListA_None ; 49 UNIT_TYPE_SUPPLY_TANKER
    dw MapAI_UnitTypeListA_Naval ; 50 UNIT_TYPE_SUBMARINE
    dw MapAI_UnitTypeListA_None ; 51 UNIT_TYPE_SUBMARINE_S

MapAI_UnitTypeListA_None::
    db UNIT_TYPE_EMPTY ; empty/terminator-only list

MapAI_UnitTypeListA_GroundHeavy::
    db UNIT_TYPE_ARTILLERY_S, UNIT_TYPE_ARTILLERY, UNIT_TYPE_ROCKET_LAUNCHER_S, UNIT_TYPE_ROCKET_LAUNCHER, UNIT_TYPE_MERCENARY_TANK, UNIT_TYPE_TANK
    db UNIT_TYPE_TANK_DESTROYER_S, UNIT_TYPE_TANK_DESTROYER, UNIT_TYPE_IFV_S, UNIT_TYPE_IFV, UNIT_TYPE_APC_S, UNIT_TYPE_APC
    db UNIT_TYPE_MERCENARY_ANTI_AIR_MISSILES, UNIT_TYPE_ANTI_AIR_TANK, UNIT_TYPE_ANTI_AIR_MISSILES_S, UNIT_TYPE_ANTI_AIR_MISSILES, UNIT_TYPE_EMPTY

MapAI_UnitTypeListA_BroadNonAir::
    db UNIT_TYPE_ARTILLERY_S, UNIT_TYPE_ARTILLERY, UNIT_TYPE_ROCKET_LAUNCHER_S, UNIT_TYPE_ROCKET_LAUNCHER, UNIT_TYPE_MERCENARY_TANK, UNIT_TYPE_TANK
    db UNIT_TYPE_TANK_DESTROYER_S, UNIT_TYPE_TANK_DESTROYER, UNIT_TYPE_IFV_S, UNIT_TYPE_IFV, UNIT_TYPE_MISSILE_INFANTRY, UNIT_TYPE_COMBAT_VEHICLE_S
    db UNIT_TYPE_COMBAT_VEHICLE, UNIT_TYPE_APC_S, UNIT_TYPE_APC, UNIT_TYPE_COMBAT_BUGGY_S, UNIT_TYPE_COMBAT_BUGGY, UNIT_TYPE_MERCENARY_INFANTRY
    db UNIT_TYPE_INFANTRY, UNIT_TYPE_CONSTRUCTION_TRUCK, UNIT_TYPE_MERCENARY_ANTI_AIR_MISSILES, UNIT_TYPE_ANTI_AIR_TANK, UNIT_TYPE_ANTI_AIR_MISSILES_S, UNIT_TYPE_ANTI_AIR_MISSILES
    db UNIT_TYPE_SUPPLY_TRUCK_S, UNIT_TYPE_SUPPLY_TRUCK, UNIT_TYPE_TRANSPORT_TRUCK_S, UNIT_TYPE_TRANSPORT_TRUCK, UNIT_TYPE_TRANSPORT_SHIP, UNIT_TYPE_SUPPLY_TANKER
    db UNIT_TYPE_MERCENARY_MISSILE_FRIGATE, UNIT_TYPE_AEGIS_WARSHIP, UNIT_TYPE_LARGE_CARRIER, UNIT_TYPE_SMALL_CARRIER, UNIT_TYPE_EMPTY

MapAI_UnitTypeListA_Air::
    db UNIT_TYPE_FIGHTER_PLANE_S, UNIT_TYPE_ATTACK_PLANE_S, UNIT_TYPE_FIGHTER_PLANE_A, UNIT_TYPE_ATTACK_PLANE_A, UNIT_TYPE_FIGHTER_PLANE_B, UNIT_TYPE_ATTACK_PLANE_B
    db UNIT_TYPE_BATTLE_HELICOPTER_S, UNIT_TYPE_BATTLE_HELICOPTER, UNIT_TYPE_ANTI_SUB_HELICOPTER, UNIT_TYPE_MERCENARY_BOMBER, UNIT_TYPE_BOMBER, UNIT_TYPE_TRANSPORT_PLANE
    db UNIT_TYPE_TRANSPORT_HELICOPTER_S, UNIT_TYPE_TRANSPORT_HELICOPTER, UNIT_TYPE_REFUELING_PLANE, UNIT_TYPE_EMPTY

MapAI_UnitTypeListA_Naval::
    db UNIT_TYPE_SUBMARINE_S, UNIT_TYPE_SUBMARINE, UNIT_TYPE_MERCENARY_MISSILE_FRIGATE, UNIT_TYPE_AEGIS_WARSHIP, UNIT_TYPE_LARGE_CARRIER, UNIT_TYPE_SMALL_CARRIER
    db UNIT_TYPE_TRANSPORT_SHIP, UNIT_TYPE_SUPPLY_TANKER, UNIT_TYPE_EMPTY

MapAI_UnitTypeListProfileTableB::
    dw MapAI_UnitTypeListB_None ;  0 UNIT_TYPE_EMPTY
    dw MapAI_UnitTypeListB_GroundLight ;  1 UNIT_TYPE_INFANTRY
    dw MapAI_UnitTypeListB_GroundLight ;  2 UNIT_TYPE_MISSILE_INFANTRY
    dw MapAI_UnitTypeListB_GroundLight ;  3 UNIT_TYPE_MERCENARY_INFANTRY
    dw MapAI_UnitTypeListB_GroundLight ;  4 UNIT_TYPE_CONSTRUCTION_TRUCK
    dw MapAI_UnitTypeListB_None ;  5 UNIT_TYPE_SUPPLY_TRUCK
    dw MapAI_UnitTypeListB_None ;  6 UNIT_TYPE_SUPPLY_TRUCK_S
    dw MapAI_UnitTypeListB_None2 ;  7 UNIT_TYPE_TRANSPORT_TRUCK
    dw MapAI_UnitTypeListB_None2 ;  8 UNIT_TYPE_TRANSPORT_TRUCK_S
    dw MapAI_UnitTypeListB_None2 ;  9 UNIT_TYPE_COMBAT_BUGGY
    dw MapAI_UnitTypeListB_None2 ; 10 UNIT_TYPE_COMBAT_BUGGY_S
    dw MapAI_UnitTypeListB_None2 ; 11 UNIT_TYPE_COMBAT_VEHICLE
    dw MapAI_UnitTypeListB_None2 ; 12 UNIT_TYPE_COMBAT_VEHICLE_S
    dw MapAI_UnitTypeListB_None2 ; 13 UNIT_TYPE_APC
    dw MapAI_UnitTypeListB_None2 ; 14 UNIT_TYPE_APC_S
    dw MapAI_UnitTypeListB_None ; 15 UNIT_TYPE_ROCKET_LAUNCHER
    dw MapAI_UnitTypeListB_None ; 16 UNIT_TYPE_ROCKET_LAUNCHER_S
    dw MapAI_UnitTypeListB_Mixed ; 17 UNIT_TYPE_ANTI_AIR_TANK
    dw MapAI_UnitTypeListB_Mixed ; 18 UNIT_TYPE_MERCENARY_ANTI_AIR_MISSILES
    dw MapAI_UnitTypeListB_None ; 19 UNIT_TYPE_ANTI_AIR_MISSILES
    dw MapAI_UnitTypeListB_None ; 20 UNIT_TYPE_ANTI_AIR_MISSILES_S
    dw MapAI_UnitTypeListB_None ; 21 UNIT_TYPE_ARTILLERY
    dw MapAI_UnitTypeListB_None ; 22 UNIT_TYPE_ARTILLERY_S
    dw MapAI_UnitTypeListB_None2 ; 23 UNIT_TYPE_IFV
    dw MapAI_UnitTypeListB_None2 ; 24 UNIT_TYPE_IFV_S
    dw MapAI_UnitTypeListB_None2 ; 25 UNIT_TYPE_TANK_DESTROYER
    dw MapAI_UnitTypeListB_None2 ; 26 UNIT_TYPE_TANK_DESTROYER_S
    dw MapAI_UnitTypeListB_None2 ; 27 UNIT_TYPE_TANK
    dw MapAI_UnitTypeListB_None2 ; 28 UNIT_TYPE_MERCENARY_TANK
    dw MapAI_UnitTypeListB_None3 ; 29 UNIT_TYPE_FIGHTER_PLANE_A
    dw MapAI_UnitTypeListB_None3 ; 30 UNIT_TYPE_FIGHTER_PLANE_B
    dw MapAI_UnitTypeListB_None3 ; 31 UNIT_TYPE_FIGHTER_PLANE_S
    dw MapAI_UnitTypeListB_None3 ; 32 UNIT_TYPE_ATTACK_PLANE_A
    dw MapAI_UnitTypeListB_None3 ; 33 UNIT_TYPE_ATTACK_PLANE_B
    dw MapAI_UnitTypeListB_None ; 34 UNIT_TYPE_ATTACK_PLANE_S
    dw MapAI_UnitTypeListB_None ; 35 UNIT_TYPE_BOMBER
    dw MapAI_UnitTypeListB_None ; 36 UNIT_TYPE_MERCENARY_BOMBER
    dw MapAI_UnitTypeListB_None ; 37 UNIT_TYPE_TRANSPORT_PLANE
    dw MapAI_UnitTypeListB_None2 ; 38 UNIT_TYPE_REFUELING_PLANE
    dw MapAI_UnitTypeListB_None ; 39 UNIT_TYPE_BATTLE_HELICOPTER
    dw MapAI_UnitTypeListB_None2 ; 40 UNIT_TYPE_BATTLE_HELICOPTER_S
    dw MapAI_UnitTypeListB_None2 ; 41 UNIT_TYPE_ANTI_SUB_HELICOPTER
    dw MapAI_UnitTypeListB_None2 ; 42 UNIT_TYPE_TRANSPORT_HELICOPTER
    dw MapAI_UnitTypeListB_None2 ; 43 UNIT_TYPE_TRANSPORT_HELICOPTER_S
    dw MapAI_UnitTypeListB_None2 ; 44 UNIT_TYPE_AEGIS_WARSHIP
    dw MapAI_UnitTypeListB_None2 ; 45 UNIT_TYPE_MERCENARY_MISSILE_FRIGATE
    dw MapAI_UnitTypeListB_None2 ; 46 UNIT_TYPE_LARGE_CARRIER
    dw MapAI_UnitTypeListB_None2 ; 47 UNIT_TYPE_SMALL_CARRIER
    dw MapAI_UnitTypeListB_None2 ; 48 UNIT_TYPE_TRANSPORT_SHIP
    dw MapAI_UnitTypeListB_None ; 49 UNIT_TYPE_SUPPLY_TANKER
    dw MapAI_UnitTypeListB_None ; 50 UNIT_TYPE_SUBMARINE
    dw MapAI_UnitTypeListB_None2 ; 51 UNIT_TYPE_SUBMARINE_S

MapAI_UnitTypeListB_None::
    db UNIT_TYPE_EMPTY ; empty/terminator-only list

MapAI_UnitTypeListB_GroundLight::
    db UNIT_TYPE_MISSILE_INFANTRY, UNIT_TYPE_MERCENARY_INFANTRY, UNIT_TYPE_INFANTRY, UNIT_TYPE_CONSTRUCTION_TRUCK, UNIT_TYPE_COMBAT_BUGGY, UNIT_TYPE_COMBAT_BUGGY_S
    db UNIT_TYPE_COMBAT_VEHICLE, UNIT_TYPE_COMBAT_VEHICLE_S, UNIT_TYPE_SUPPLY_TRUCK_S, UNIT_TYPE_SUPPLY_TRUCK, UNIT_TYPE_TRANSPORT_TRUCK_S, UNIT_TYPE_TRANSPORT_TRUCK
    db UNIT_TYPE_EMPTY

MapAI_UnitTypeListB_None2::
    db UNIT_TYPE_EMPTY ; empty/terminator-only list

MapAI_UnitTypeListB_Mixed::
    db UNIT_TYPE_FIGHTER_PLANE_S, UNIT_TYPE_FIGHTER_PLANE_A, UNIT_TYPE_FIGHTER_PLANE_B, UNIT_TYPE_MERCENARY_BOMBER, UNIT_TYPE_BOMBER, UNIT_TYPE_ATTACK_PLANE_S
    db UNIT_TYPE_ATTACK_PLANE_A, UNIT_TYPE_ATTACK_PLANE_B, UNIT_TYPE_TRANSPORT_HELICOPTER_S, UNIT_TYPE_TRANSPORT_HELICOPTER, UNIT_TYPE_BATTLE_HELICOPTER_S, UNIT_TYPE_BATTLE_HELICOPTER
    db UNIT_TYPE_ANTI_SUB_HELICOPTER, UNIT_TYPE_TRANSPORT_PLANE, UNIT_TYPE_REFUELING_PLANE, UNIT_TYPE_INFANTRY, UNIT_TYPE_CONSTRUCTION_TRUCK, UNIT_TYPE_TRANSPORT_TRUCK_S
    db UNIT_TYPE_TRANSPORT_TRUCK, UNIT_TYPE_SUPPLY_TRUCK_S, UNIT_TYPE_SUPPLY_TRUCK, UNIT_TYPE_COMBAT_BUGGY, UNIT_TYPE_MERCENARY_INFANTRY, UNIT_TYPE_MISSILE_INFANTRY
    db UNIT_TYPE_ARTILLERY_S, UNIT_TYPE_ARTILLERY, UNIT_TYPE_ROCKET_LAUNCHER_S, UNIT_TYPE_ROCKET_LAUNCHER, UNIT_TYPE_ANTI_AIR_MISSILES_S, UNIT_TYPE_ANTI_AIR_MISSILES
    db UNIT_TYPE_APC, UNIT_TYPE_EMPTY

MapAI_UnitTypeListB_None3::
    db UNIT_TYPE_EMPTY ; empty/terminator-only list

    assert @ == $4b91
